FROM python:3.7-alpine

RUN apk add --update build-base ca-certificates make
RUN apk add \
    libjpeg \
    zlib \
    zlib-dev \
    libwebp \
    openjpeg \
    jpeg-dev \
    postgresql-libs \
    postgresql-dev \
    ncurses-dev \
    readline-dev \
    bash

WORKDIR /app
COPY /project /app
RUN make req

EXPOSE 8000